import './style.css';

const engines=[{id:'i4',name:'2.0L Inline-4',type:'Petrol · 4-cylinder',desc:'Compact everyday architecture.',specs:['1998 cc','4 cylinders','DOHC','16 valves']},{id:'v6',name:'3.0L V6',type:'Petrol · 6-cylinder',desc:'Two banks arranged in a V.',specs:['2995 cc','6 cylinders','DOHC','24 valves']},{id:'diesel',name:'2.2L Turbo Diesel',type:'Diesel · 4-cylinder',desc:'High-compression turbo architecture.',specs:['2198 cc','4 cylinders','Turbo','16 valves']},{id:'bike',name:'1.0L Motorcycle',type:'Petrol · 4-cylinder',desc:'High-revving motorcycle architecture.',specs:['998 cc','4 cylinders','DOHC','16 valves']}];
const parts=[['Engine block','Structural body containing cylinders, bearing supports and fluid passages.'],['Cylinder head','Closes the cylinders and houses valves and combustion hardware.'],['Piston','Reciprocates in the cylinder and receives combustion force.'],['Piston rings','Seal combustion gases, control oil and transfer heat.'],['Connecting rod','Links piston to crankshaft and transmits cyclic loads.'],['Crankshaft','Converts reciprocating motion into rotational motion.'],['Camshaft','Uses lobes to control valve timing.'],['Intake valve','Admits fresh charge into the cylinder.'],['Exhaust valve','Releases combustion products.'],['Fuel injector','Meters and atomizes fuel.'],['Spark plug','Ignites compressed charge in petrol engines.'],['Timing drive','Synchronizes crankshaft and camshaft rotation.'],['Oil pump','Circulates pressurized lubricant.'],['Oil filter','Removes contaminants from engine oil.'],['Coolant jacket','Carries heat away from block and head.'],['Thermostat','Regulates coolant flow and operating temperature.'],['Flywheel / flexplate','Stores rotational energy and couples the crankshaft.'],['Turbocharger','Uses exhaust energy to compress intake air.'],['Throttle body','Controls intake air flow.'],['Exhaust manifold','Collects exhaust gases from cylinders.']];

function engineSvg(kind='i4',exploded=false){
  const xs=kind==='v6'?[70,130,190,310,370,430]:[105,180,255,330];
  let cylinders='';
  xs.forEach((x)=>{cylinders+=`<g class="piece" data-part="Piston"><rect x="${x}" y="125" width="45" height="145" rx="12" fill="#eee" stroke="#999" stroke-width="4"/><rect x="${x+5}" y="${exploded?175:145}" width="35" height="60" rx="8" fill="#bbb" stroke="#777" stroke-width="3"/><line x1="${x+22}" y1="${exploded?235:205}" x2="${x+22}" y2="385" stroke="#777" stroke-width="7"/></g>`});
  return `<svg viewBox="0 0 500 520"><defs><linearGradient id="metal" x1="0" x2="1"><stop stop-color="#ddd"/><stop offset=".5" stop-color="#999"/><stop offset="1" stop-color="#ddd"/></linearGradient></defs><rect x="40" y="100" width="420" height="295" rx="24" fill="url(#metal)" stroke="#666" stroke-width="5" data-part="Engine block"/><rect x="53" y="72" width="394" height="62" rx="18" fill="#bdbdbd" stroke="#707070" stroke-width="5" data-part="Cylinder head"/>${cylinders}<g data-part="Crankshaft"><rect x="70" y="387" width="360" height="30" rx="15" fill="#3a3a3a"/><circle cx="120" cy="402" r="23" fill="#555"/><circle cx="200" cy="402" r="23" fill="#555"/><circle cx="280" cy="402" r="23" fill="#555"/><circle cx="360" cy="402" r="23" fill="#555"/></g><g data-part="Camshaft"><rect x="78" y="48" width="344" height="16" rx="8" fill="#333"/></g><g data-part="Turbocharger"><circle cx="420" cy="250" r="42" fill="#777" stroke="#444" stroke-width="7"/><circle cx="420" cy="250" r="15" fill="#bbb"/></g><text x="250" y="495" text-anchor="middle" fill="#777" font-size="15" font-family="Arial">Drag · scroll · select a part</text></svg>`;
}

let state={engine:engines[0],part:parts[0],exploded:false,search:'',section:'atlas',zoom:1};
document.querySelector('#app').innerHTML=`<header class="topbar"><div class="brand">ENGINE <span>ATLAS</span></div><div class="searchWrap">⌕ <input id="search" placeholder="Search engines, parts, systems…"></div><nav><button data-section="atlas">Library</button><button data-section="learn">Learn</button><button data-section="compare">Compare</button></nav><div class="avatar">S</div></header><main class="shell"><section class="hero"><div><div class="eyebrow">MICRO-MECHANICS EXPLORER</div><h1>Understand what moves<br>under the hood.</h1><p>Explore everyday car and motorcycle engines part-by-part, reveal hidden mechanisms, and trace how combustion becomes motion.</p></div><div class="heroStat"><div class="metric"><b>20+</b><span>interactive parts</span></div><div class="metric"><b>4</b><span>engine families</span></div></div></section><section id="content"></section></main>`;

function render(){const c=document.querySelector('#content');if(state.section==='atlas')renderAtlas(c);else if(state.section==='learn')renderLearn(c);else renderCompare(c);document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===state.section));}
function renderAtlas(c){const filtered=parts.filter(p=>p[0].toLowerCase().includes(state.search.toLowerCase()));c.innerHTML=`<div class="grid2"><aside class="panel engines"><div class="panelHead"><div><span class="label">ENGINE LIBRARY</span><h2>Choose a powerplant</h2></div><span class="count">${engines.length}</span></div>${engines.map(e=>`<button class="engineCard ${e.id===state.engine.id?'selected':''}" data-engine="${e.id}"><div class="thumb"><div class="miniBlock"></div><div class="miniCyl a"></div><div class="miniCyl b"></div><div class="miniCrank"></div></div><div><b>${e.name}</b><small>${e.type}</small><span>${e.desc}</span></div><i>›</i></button>`).join('')}</aside><section class="viewer panel"><div class="viewerTop"><div><span class="label">3D SIMULATION</span><h2>${state.engine.name}</h2></div><div class="controls"><button id="explode">${state.exploded?'ASSEMBLE':'EXPLODE'}</button><button id="reset">RESET</button></div></div><div class="stage"><div class="hotspot h1" data-part="Piston">01</div><div class="hotspot h2" data-part="Crankshaft">02</div><div class="hotspot h3" data-part="Camshaft">03</div><div class="model" style="transform:scale(${state.zoom})">${engineSvg(state.engine.id,state.exploded)}</div><div class="zoomBar"><button id="minus">−</button><div class="bar"><span style="width:${((state.zoom-.8)/.8)*100}%"></span></div><button id="plus">+</button></div></div><div class="info"><div class="infoTag">SELECTED PART</div><h3>${state.part[0]}</h3><p>${state.part[1]}</p><div class="specRow">${state.engine.specs.map(s=>`<span>${s}</span>`).join('')}</div></div></section></div><section class="parts panel"><div class="panelHead"><div><span class="label">PARTS CATALOGUE</span><h2>Everything inside the machine</h2></div><span class="muted">Click a part to inspect</span></div><div class="partGrid">${filtered.map((p,i)=>`<button class="partCard ${p[0]===state.part[0]?'selected':''}" data-part="${p[0]}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${p[0]}</b><small>${p[1]}</small></div><i>↗</i></button>`).join('')}</div></section>`;bindAtlas();}
function renderLearn(c){const items=['Intake valve opens and the piston moves down, drawing charge in.','Both valves close and the piston travels upward, compressing the charge.','Ignition raises cylinder pressure and pushes the piston down.','The exhaust valve opens and the piston pushes spent gases out.'];c.innerHTML=`<div class="learn panel"><span class="label">LEARN</span><h2>The four-stroke cycle</h2><p class="lead">A typical four-stroke spark-ignition engine repeats intake, compression, power and exhaust. The crankshaft completes two revolutions for one complete cycle.</p><div class="steps">${['Intake','Compression','Power','Exhaust'].map((s,i)=>`<article><div class="stepNum">0${i+1}</div><h3>${s}</h3><p>${items[i]}</p></article>`).join('')}</div><div class="note"><b>Engineering note</b><span>Modern road engines can add direct injection, variable valve timing, turbocharging and advanced emissions hardware.</span></div></div>`;}
function renderCompare(c){c.innerHTML=`<div class="panel compare"><span class="label">COMPARE</span><h2>Engine families at a glance</h2><table><thead><tr><th>Engine</th><th>Configuration</th><th>Displacement</th><th>Valve train</th></tr></thead><tbody>${engines.map(e=>`<tr><td><b>${e.name}</b></td><td>${e.type}</td><td>${e.specs[0]}</td><td>${e.specs[2]} · ${e.specs[3]}</td></tr>`).join('')}</tbody></table></div>`;}
function bindAtlas(){document.querySelectorAll('[data-engine]').forEach(b=>b.onclick=()=>{state.engine=engines.find(e=>e.id===b.dataset.engine);state.part=parts[0];state.zoom=1;state.exploded=false;render()});document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{const f=parts.find(p=>p[0]===b.dataset.part);if(f){state.part=f;render()}});document.querySelector('#explode').onclick=()=>{state.exploded=!state.exploded;render()};document.querySelector('#reset').onclick=()=>{state.zoom=1;state.exploded=false;render()};document.querySelector('#plus').onclick=()=>{state.zoom=Math.min(1.6,+(state.zoom+.1).toFixed(2));render()};document.querySelector('#minus').onclick=()=>{state.zoom=Math.max(.8,+(state.zoom-.1).toFixed(2));render()};}
document.querySelector('#search').addEventListener('input',e=>{state.search=e.target.value;state.section='atlas';render()});document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;render()});render();